---
- name: Installation du serveur
  hosts: all
  gather_facts: no
  become: yes
  remote_user: "{{ remote_default_user  }}"

  tasks:
  - name: Include default variables
    include_vars: "{{ playbooks_directory_path }}/variables/default.yml"

  - name: Include password file
    include_vars: "{{ stub_deploy_password_file_path }}"

  - name: Update & Upgrade
    apt:
      update_cache: yes
      upgrade: dist

  - name: Include tools file
    include_tasks: "{{ playbooks_directory_path }}/install/tools.yml"

  - name: Include zsh file
    include_tasks: "{{ playbooks_directory_path }}/install/zsh.yml"

  - name: Include vim file
    include_tasks: "{{ playbooks_directory_path }}/install/vim.yml"

  - name: Include firewall file
    include_tasks: "{{ playbooks_directory_path }}/install/firewall.yml"

  - name: Include php file
    include_tasks: "{{ playbooks_directory_path }}/install/php.yml"

  - name: Include composer file
    include_tasks: "{{ playbooks_directory_path }}/install/composer.yml"

  - name: Include database file
    include_tasks: "{{ playbooks_directory_path }}/install/database.yml"

  - name: Include nodejs file
    include_tasks: "{{ playbooks_directory_path }}/install/nodejs.yml"

  - name: Include nginx file
    include_tasks: "{{ playbooks_directory_path }}/install/nginx.yml"

  - name: Include redis file
    include_tasks: "{{ playbooks_directory_path }}/install/redis.yml"

  - name: Include postfix file
    include_tasks: "{{ playbooks_directory_path }}/install/postfix.yml"
