---
- name: Deploy .env file
  hosts: all
  gather_facts: no
  remote_user:  "{{ user }}"
  vars:
    force_deploy: true
    current_shared_path: "/home/{{ user }}/{{ domain }}/shared"

  tasks:
  - name: Include default variables
    include_vars: "{{ playbooks_directory_path }}/variables/default.yml"

  - name: Include variables
    include_vars: "{{ playbooks_directory_path }}/variables/db.yml"

  - name: Include password file
    include_vars: "{{ stub_deploy_password_file_path }}"

  - name: Include env task
    include_tasks: "{{ playbooks_directory_path }}/deploy/steps/env.yml"
