---
- name: Dump mysql database
  hosts: all
  gather_facts: no
  remote_user:  "{{ user }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_winrm_server_cert_validation: ignore
    dump_path: "/home/{{ user }}/{{ application }}database.sql"
  tasks:

  - name: Include password file
    include_vars: "{{ project_path }}/deploy-passwords.yml"

  - name: Dump database
    mysql_db:
      state: dump
      name: "{{ database_name }}"
      login_user: "{{ database_user }}"
      login_password: "{{ vault_database_password }}"
      target: "{{ dump_path }}"

  - name: Copy file from remote to host
    fetch:
      src: "{{ dump_path }}"
      dest: "{{ project_path }}/"
      flat: yes

  - name: Delete remote archive
    file:
      path: "{{ dump_path }}"
      state: absent
