---
- name: Installation du serveur
  hosts: all
  gather_facts: no
  become: yes
  remote_user: "{{ remote_default_user | default('root')  }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_winrm_server_cert_validation: ignore

  tasks:
  - name: Update & Upgrade
    apt:
      update_cache: yes
      upgrade: dist

  - name: Include vars file
    include_vars: "{{ playbooks_directory_path }}/variables/vars.yml"

  - name: Include password file
    include_vars: "{{ project_path }}/deploy-passwords.yml"

  - name: Include tools file
    include_tasks: "{{ playbooks_directory_path }}/install/tools.yml"

  - name: Include zsh file
    include_tasks: "{{ playbooks_directory_path }}/install/zsh.yml"

  - name: Include vim file
    include_tasks: "{{ playbooks_directory_path }}/install/vim.yml"

  - name: Include firewall file
    include_tasks: "{{ playbooks_directory_path }}/install/firewall.yml"

  - name: Include php file
    include_tasks: "{{ playbooks_directory_path }}/install/php.yml"

  - name: Include composer file
    include_tasks: "{{ playbooks_directory_path }}/install/composer.yml"

  - name: Include mysql file
    include_tasks: "{{ playbooks_directory_path }}/install/mysql.yml"

  - name: Include nodejs file
    include_tasks: "{{ playbooks_directory_path }}/install/nodejs.yml"

  - name: Include nginx file
    include_tasks: "{{ playbooks_directory_path }}/install/nginx.yml"

  - name: Include redis file
    include_tasks: "{{ playbooks_directory_path }}/install/redis.yml"

  - name: Include postfix file
    include_tasks: "{{ playbooks_directory_path }}/install/postfix.yml"
