---
- name: Include cron file
  include_tasks: "{{ playbooks_directory_path }}/deploy/steps/dkim.yml"

- name: Include chown_deploy_folder file
  include_tasks: "{{ playbooks_directory_path }}/deploy/steps/chown_deploy_folder.yml"

- name: Include remove_archive_folder_locally file
  include_tasks: "{{ playbooks_directory_path }}/deploy/steps/remove_archive_folder_locally.yml"


