---
- name: ANSISTRANO | Remove archive and project folder locally
  delegate_to: localhost
  become_user: "{{ remote_default_user }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ temporary_dir }}/{{ archive }}.zip"
